### ISSUE TITLE
Demo for running double buffering in Python.

### ISSUE THREAD

**Issue by WuZhuoran** [spcl/dace#1]
Ask for a demo or usage for running double buffering in Python.

**Comment by tbennun** [comment]
@WuZhuoran We added an example of using the `DoubleBuffering` transformation. 

If you go to [double_buffering_test.py](https://github.com/spcl/dace/blob/master/tests/double_buffering_test.py), you will see an example dace program that can be transformed. Here is the SDFG below and exactly what matches (the map and internal transient arrays):

![image](https://user-images.githubusercontent.com/8348955/71626029-51542780-2beb-11ea-90a9-1a8ce02686c4.png)

Upon transformation, the map will become a loop, a dimension will be added to the transients (creating the double buffers), and the data will be loaded in an alternating fashion.

Here is the end result:
![image](https://user-images.githubusercontent.com/8348955/71625934-d1c65880-2bea-11ea-8c5e-44a6e6b20b6c.png)


Hope this helps! Let us know if you have any further questions.
