### ISSUE TITLE
inline multistate error

### ISSUE THREAD

**Issue by baaiy0610** [spcl/dace#1047]
**Describe the bug**
Error when a dace is called by a dace function

**To Reproduce**
just run it

**Expected behavior**
the result mid_rad == test

**Screenshots**
![image](https://user-images.githubusercontent.com/53456502/178158342-db1c82fe-7e3f-4c87-94e0-ac659fbbb354.png)

**Comment by tbennun** [comment]
@baaiy0610 can you please post the code in text form so we can copy and test it?

**Comment by baaiy0610** [comment]
No problem!

import numpy as np
import dace

def deg_to_rad(a):
    res = np.zeros((2,))

    res[0] = a[0] * np.pi/180.0
    res[1] = a[1] * np.pi/180.0
    return res

@dace.program
def mid_rad(a: dace.float64[2], b: dace.float64[2])->dace.float64[2]:
    mid_deg = (a+b) / 2.0
    mid_rad = deg_to_rad(mid_deg)
    return mid_rad

@dace.program
def test(point1: dace.float64[2], point2: dace.float64[2]):
    return mid_rad(point1, point2)


a = np.array([30.0, 60.0])
b = np.array([40.0, 50.0])
mid_rad(a,b)

np.deg2rad((a+b)/2.0)
test(a,b)

**Comment by tbennun** [comment]
Should be fixed in #1048

**Comment by baaiy0610** [comment]
@tbennun Thanks a lot!
