### ISSUE TITLE
function numpy.max() 

### ISSUE THREAD

**Issue by baaiy0610** [spcl/dace#1064]
When i use ```np.max()``` or ```np.min()``` in dace, it will be very slow when the computational workload is very heavy, maybe you could try to look into this

**Comment by tbennun** [comment]
This is because by default it expands to the native, unoptimized SDFG (`pure`) version, which has atomic operations. 
You can use `auto_optimize` to get better performance, and we are looking into specifically improving reductions.

Hope this helps.
