### ISSUE TITLE
Intel MKL FATAL ERROR

### ISSUE THREAD

**Issue by sumuzhe317** [spcl/dace#1135]
**Describe the bug**
Excuse me. When I used IntelMKL+MPICH to run the distributed polybench.py, I have some problems with the IntelMKL. The error message is that "Intel MKL FATAL ERROR: Cannot load symbol MKLMPI_Get_wrappers.". I don't know whether it's the problem with my environment. After trying to modify the link args in dace.conf, I still couldn't handle it. I would be appreciate if you could give me some help. Thanks for your help!

**To Reproduce**
1. spack load Intel-oneapi-mkl@2022.1.0
2. spack load mpich 4.0.2
3. run the command:" `which mpirun` -genvall -n 2 -hosts node1:1,node2:1 `which python3` $(pwd)/samples/distributed/polybench.py"
4. See error Intel MKL FATAL ERROR: Cannot load symbol MKLMPI_Get_wrappers.

**Expected behavior**
run the distributed polybench.py to get the answer

**Screenshots**
![image](https://user-images.githubusercontent.com/70623068/199389731-c3d0b1de-8ca2-4259-89a1-cae520b0c18f.png)

**Desktop (please complete the following information):**
 - OS: Debian

**Comment by alexnick83** [comment]
It looks like some specific MKL library file (the one defining `MKLMPI_Get_wrappers`) is not found (but others are). To debug the issue, I would get a minimal program (find an example online or maybe reorganize a bit the code generated for `atax`) and try to compile it and run it manually using Intel's [Link Line Advisor](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html). Then, I would edit the [environment file](https://github.com/spcl/dace/blob/master/dace/libraries/pblas/environments/intel_mkl_mpich.py), specifically [line 159](https://github.com/spcl/dace/blob/14c00e5731d136a1a13d1eeff21036e8a1f8a9a2/dace/libraries/pblas/environments/intel_mkl_mpich.py#L159), to link correctly to the required libraries. It may also be a PATH issue; perhaps you need to run Intel's `setvars` scripts (if the spack module is not doing that automatically) or set your `LD_LIBRARY_PATH` manually. In the same file, [line 58](https://github.com/spcl/dace/blob/14c00e5731d136a1a13d1eeff21036e8a1f8a9a2/dace/libraries/pblas/environments/intel_mkl_mpich.py#L58), you can find the method used to located the MKL libraries. Perhaps you could run it separately and see if the folder found includes all the MKL libraries needed for linking.

**Comment by sumuzhe317** [comment]
> It looks like some specific MKL library file (the one defining `MKLMPI_Get_wrappers`) is not found (but others are). To debug the issue, I would get a minimal program (find an example online or maybe reorganize a bit the code generated for `atax`) and try to compile it and run it manually using Intel's [Link Line Advisor](https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html). Then, I would edit the [environment file](https://github.com/spcl/dace/blob/master/dace/libraries/pblas/environments/intel_mkl_mpich.py), specifically [line 159](https://github.com/spcl/dace/blob/14c00e5731d136a1a13d1eeff21036e8a1f8a9a2/dace/libraries/pblas/environments/intel_mkl_mpich.py#L159), to link correctly to the required libraries. It may also be a PATH issue; perhaps you need to run Intel's `setvars` scripts (if the spack module is not doing that automatically) or set your `LD_LIBRARY_PATH` manually. In the same file, [line 58](https://github.com/spcl/dace/blob/14c00e5731d136a1a13d1eeff21036e8a1f8a9a2/dace/libraries/pblas/environments/intel_mkl_mpich.py#L58), you can find the method used to located the MKL libraries. Perhaps you could run it separately and see if the folder found includes all the MKL libraries needed for linking.

thanks for your help.
