### ISSUE TITLE
Warn user when calling `to_sdfg` on a function that shouldn't be reparsed

### ISSUE THREAD

**Issue by tbennun** [spcl/dace#1175]
When using `reparse_sdfg` or `recompile` keyword arguments:
1. sometimes recompile shows up as a constant expression
2. if calling `to_sdfg()` the user should be warned that these arguments will be ignored.

**Comment by tbennun** [comment]
To start with this, I would go to the [dace/frontend/python](https://github.com/spcl/dace/tree/master/dace/frontend/python) folder and the [relevant documentation page](https://spcldace.readthedocs.io/en/latest/frontend/python.html).

**Comment by HarshvMahawar** [comment]
I am new here, can you please elaborate on what has to be done and proceeding steps, thanks

**Comment by tbennun** [comment]
After looking at the documentation, please look at #1204 for more information regarding the issue.
