### ISSUE TITLE
Parsing error while calling an array getter twice

### ISSUE THREAD

**Issue by rd-cea** [spcl/dace#1250]
**Bug**

When a function that returns an array is called twice in a parallel loop, an error occurs at the second function call:
`NameError: Array "__g_<ARRAY_NAME>_0" not found in outer scope or closure`

Calling the function once, or accessing the array directly multiple times do not cause any error.

**To Reproduce**

The following code causes a DaCe error on lines `quads1 = get_quads()` / `quads1 = get_quads_alt()`:

```python
import dace
import numpy as np

NB_CELLS = 100
NB_QUADS = 20
QUADS = np.empty((NB_QUADS, 4), dtype=np.int32)


def get_quads():
    return QUADS


def get_quads_alt():
    return QUADS


@dace.program
def call_getter_twice():
    """
    Call the array getter twice per iteration
    [ERR] NameError: Array "__g_QUADS_0" not found in outer scope or closure
    """
    start_index = 0
    for j_cells in dace.map[start_index:NB_CELLS]:
        j_id0 = j_cells
        quads0 = get_quads()
        nodes_of_cell_j0 = quads0[j_id0]
        # ...Computation...

        j_id1 = j_cells
        # quads1 = get_quads()   # <- Error is caused by this function call...
        quads1 = get_quads_alt() # <- ...or alternatively by this one
        nodes_of_cell_j1 = quads1[j_id1]
        # ...Computation...


if __name__ == '__main__':
    call_getter_twice() # Error
```

**Expected behavior**

No DaCe error is thrown. Same result as accessing the array directly, without a function call (`quads0 = QUADS`, `quads1 = QUADS`).

**Desktop:**
 - OS: Ubuntu 22.04
 - DaCe 0.14.2

**Motivation**

Our aim is to generate DaCe code from a higher-level domain-specific language. Even though calling the same getter twice may be pointless, such code is expected to be valid.

Our current generator initializes multiple variables before their usage in next loop. At the moment, these variables cannot be reused among subsequent loops. For that reason, the same getter can be called multiple times, as shown in the following code snippet:
```python
for j_cells in dace.map[start_index:self._nbCells]:
  j_id = j_cells

  # Loop #0 - Initialization
  reduction0 = dace.ndarray((2), dtype=dace.float64)
  reduction0.fill(0.0)
  nodes_of_cell_j0 = get_quads(j_id) # <- First call to get_quads()
  nb_nodes_of_cell_j0 = nodes_of_cell_j0.size

  # Loop #0 - Loop Construct
  for r_nodes_of_cell_j0 in range(nb_nodes_of_cell_j):
    r_id0 = nodes_of_cell_j0[r_nodes_of_cell_j]
    reduction0 = ...

  # Loop #1 - Initialization
  reduction1 = 0.0
  nodes_of_cell_j1 = get_quads(j_id)  # <- Second call to get_quads()
  nb_nodes_of_cell_j1 = nodes_of_cell_j1.size

  # Loop #1 - Loop Construct
  for rNodesOfCellJ in range(nbNodesOfCellJ):
    r_id1 = nodesOfCellJ[rNodesOfCellJ]
    reduction1 = ...
```

**Comment by alexnick83** [comment]
> Thank you for reporting and for the short reproducer. It's probably an error in the internal mapping of `QUADS` inside the dace python parser. It is correct to only feed it in as one argument (since the array will be shared across the two calls), hence the `_0`.
> 
> Does it also happen if you just call `get_quads` twice rather than `get_quads_alt`?

It is a more complicated issue because, in the above code, the return values of the methods are views to the global `QUADS`. We do not support returning views from DaCe programs, but we make a copy, which may yield different semantics than expected.

**Comment by rd-cea** [comment]
> Does it also happen if you just call `get_quads` twice rather than `get_quads_alt`?

Thanks for your quick reply. I confirm the same error occurs when `get_quads` is called twice.

**Comment by alexnick83** [comment]
@rd-cea We are in the process of fixing the reported error. A potential follow-up issue concerns what is returned from `get_quads` and `get_quads_alt`. In CPython, these methods will return a reference to the global array `QUADS`. In other words, if you write to `quads0` in your example program above, then the changes will be immediately seen in `QUADS` and `quads1`. However, DaCe does not support returning such references (through the `return` statements). Instead, it will return copies, and `QUADS`, `quads0`, and `quads1` will be different objects. If this will be an issue, please let us know, so we can discuss a workaround for your use case.

**Comment by alexnick83** [comment]
@rd-cea We have now merged the fix into the master branch. Could you try it with your code?
