### ISSUE TITLE
DaCe does not warn on excess arguments to `dace.program`

### ISSUE THREAD

**Issue by computablee** [spcl/dace#1263]
**Describe the bug**
When passing more arguments to a function annotated with `@dace.program`, DaCe fails to warn the user.

**To Reproduce**
```py
import dace

IMGDIM = dace.symbol('IMGDIM')

@dace.program
def imgcpy(img1: dace.float64[IMGDIM, IMGDIM], img2: dace.float64[IMGDIM, IMGDIM], coefficient: dace.float64):
    img1[:, :] = img2[:, :] * coefficient

imgcpy([[1, 2], [3, 4]], [[4, 3], [2, 1]], 0.0, 1.0)
```
Full output:
```
user@linux:~/Temp/dace$ python3 bug_reproducer.py 
WARNING: Casting list argument "img1" to ndarray
WARNING: Casting list argument "img2" to ndarray
```

**Expected behavior**
A notice that more arguments are being passed to `imgcpy` than `imgcpy` accepts.

**Desktop (please complete the following information):**
 - OS: Linux Mint 21.1 "Vera"
 - DaCe Version: 0.14.2

**Comment by tbennun** [comment]
Fixed in #1283
