### ISSUE TITLE
Dependency Conflict in requirements.txt

### ISSUE THREAD

**Issue by oelbert** [spcl/dace#1264]
**Describe the bug**
`pip install -r requirements.txt` fails due to dependency conflicts between flask and click, Werkzeug, itsdangerous, and Jinja, as well as between Jinja and markupsafe.

**To Reproduce**
1. clone the repository
2. run `pip install -r requirements.txt`

**Comment by tbennun** [comment]
Thank you for reporting. We don’t maintain requirements.txt often, we will update it but for now we recommend using setup.py

**Comment by tbennun** [comment]
Fixed in #1270. Please verify that it works for you so we can close the issue.
