### ISSUE TITLE
Request for bitshift operators be added to symbols

### ISSUE THREAD

**Issue by computablee** [spcl/dace#1315]
# Current limitations
Currently, bitshift operators (e.g., `<<` and `>>`) throw the following error when applied to dace symbols:
```
TypeError: unsupported operand type(s) for >>: 'symbol' and 'int'
```
This might be something one would like to do on an iteration variable within a `dace.map`. For instance:
```py
@dace.program
def f(a):
    for i in dace.map[0:16:2]:
        a[i] = i >> 1
```
This function runs under the python interpreter:
```py
arr1 = np.zeros(16, dtype=np.int32)

f.f(arr1)
print(arr1) #[0 0 1 0 2 0 3 0 4 0 5 0 6 0 7 0]
```
But not under DaCe, giving the aforementioned `TypeError`.

# Current workarounds
Currently I have been using the following two workarounds:
```py
@dace.program
def f(a):
    for i in dace.map[0:16:2]:
        a[i] = int(i) >> 1
```
This workaround is a very low-effort workaround which doesn't require much explanation. Simply converting the symbol into an integer causes the code to run. Alternatively, integer division and multiplication _are_ implemented for symbols, so you could alternatively do:
```py
@dace.program
def f(a):
    for i in dace.map[0:16:2]:
        a[i] = i // 2
```
This is the workaround I have been using.

# Motivation
The workarounds are very easy to do, so I would consider this a very low-priority feature request. However, they can end up cluttering code a little bit. The symbol multiplication/division workaround may not be very self-explanatory and will also generate C++/CUDA code which does not use bitshifts. A good compiler should identify this and convert them into bitshifts, but this is not always guaranteed in my experience. The former workaround by converting a symbol to an integer will convert an `int`-represented symbol to a `long long` first via `dace::int64()`, which may be undesirable if doing a left bit shift, for instance.

# Proposed solution
I've not had the time to fully understand the DaCe codebase, nor is that a priority for me right now, but I propose adding an overload for `int`-represented symbols to implement bitshift operators natively on the 32-bit format, without having to first convert to a 64-bit integer and without generating multiplications or divisions in the target language.

**Comment by alexnick83** [comment]
The semantics are a bit unclear with symbols. As you noted, there is an open question on the (exact) type of `i`. Perhaps it should be the same type as the LHS of the assignment (if it is an integer). In any case, I propose that you explicitly convert to int32 for your workaround with `dace.int32(i)` or `np.int32(i)`. We consider Python ints to be 64-bit.
