### ISSUE TITLE
Missing declaration of interstate symbol in generated code.

### ISSUE THREAD

**Issue by gronerl** [spcl/dace#1319]
This simple graph fails to compile since the declaration of `wsym` is missing from the generated code. The failure only occurs if fuse_states is called.

```
import dace
from dace.transformation.passes.fusion_inline import fuse_states

sdfg = dace.SDFG('demo')
s1 = sdfg.add_state('loop_1')
t= s1.add_tasklet('tlet', code='_out = 1.0', outputs={'_out'}, inputs={})
s1.add_edge(t, '_out', s1.add_access('scalar'), None, dace.Memlet('scalar[0]'))
sdfg.add_scalar('scalar', dtype=dace.float64)
s2 = sdfg.add_state('loop_2')
edge = sdfg.add_edge(s1, s2, dace.InterstateEdge(assignments={'wsym': 'scalar'}))
sdfg.add_loop(sdfg.add_state(), s1, sdfg.add_state(), loop_end_state=s2, loop_var='ctr', initialize_expr='0', increment_expr='ctr+1', condition_expr='ctr < 10')

sdfg.add_symbol('wsym', dace.float64)

fuse_states(sdfg) # <-- compilation succeeds if this is commented.

sdfg.compile()
```
I suspect this is a bug in code generation. 

This is a reduced reproducer from an example where this issue appears as a result of applying nest_sdfg_subgraph on the loop body. Should you conclude that this graph is invalid, there would therefore be a follow-up bug there.

**Comment by alexnick83** [comment]
@gronerl #1320 is fixing the reduced reproducer and will be merged to master soon. Please check what is the status of your larger example and let us know if there are any issues remaining.
