### ISSUE TITLE
performance degradation between v0.13.3 and v0.14

### ISSUE THREAD

**Issue by rohanrayan** [spcl/dace#1350]
**Describe the bug**
There seems to be a significant slowdown of compiled code between 0.13.3 and 0.14 onwards. 

**To Reproduce**
Try to run the benchmarking.ipynb, loop example with v0.13.3 and v0.14. 
The loop example executes much faster in 0.13.3 when compared to 0.14

**Comment by tbennun** [comment]
@rohanrayan Why was this issue closed?

**Comment by rohanrayan** [comment]
@tbennun  Honestly, I am getting some inconsistent results and I am not sure if it is because of dace or my machine. I will try it with a quieter system (disable adaptive clockspeed scaling, dont run any other processes etc) and get back with more details on the issue.
