### ISSUE TITLE
More than one HBM bank with automatic SDFG generation

### ISSUE THREAD

**Issue by gabrielrodcanal** [spcl/dace#1351]
Hi there,

**Describe the bug**
I am building an SDFG from a kernel ported to Python like this:
```
sdfg = kernel.to_sdfg()
sdfg.apply_transformations(FPGATransformSDFG)
sdfg(u=u,v=v)
```

By default, this connects every kernel port to HBM[0]. Is there any way to modify this? I want to run this kernel efficiently on big sizes, and for that I need to be able to map the kernel ports to memory banks other than HBM[0].

**To Reproduce**
1. Save the following kernel as `issue_kernel.py`
```
import dace
import numpy as np
from dace.transformation.interstate import FPGATransformSDFG

DIM_X = 256
DIM_Y = 256
DIM_Z = 128


@dace.program
def issue_kernel(u:dace.float64[DIM_X,DIM_Y,DIM_Z],v:dace.float64[DIM_X,DIM_Y,DIM_Z]):
    nx = DIM_X
    ny = DIM_Y
    nz = DIM_Z

    for i in range(nx):
        for j in range(ny):
            for k in range(nz):
                u[i,j,k] = 10.0
                v[i,j,k] = 20.0



if __name__ == "__main__":
    u = np.array([[[0 for k in range(DIM_X)] for j in range(DIM_Y)] for i in range(DIM_Z)], dtype=np.double)
    v = np.array([[[0 for k in range(DIM_X)] for j in range(DIM_Y)] for i in range(DIM_Z)], dtype=np.double)

    sdfg = issue_kernel.to_sdfg()
    sdfg.apply_transformations(FPGATransformSDFG)
    sdfg(u=u,v=v)
```
2. Run `python3 issue_kernel.py`.

The `link.cfg` file under `.dacecache/issue_kernel/src/xilinx/device/` doesn't connect the kernel ports to memory banks. Hence, every port is connected to HBM[0]. The host code is generated accordingly, so although we can get a bitstream properly connected modifying this file manually, the run will fail with error `memidx == -1`.

How can we generate this connectivity without altering the kernel code? I've seen this is usually done by building the SDFG manually: https://github.com/spcl/dace/blob/master/samples/fpga/gemm_systolic_vectorized.py. I would rather not do this.

Best,
Gabriel

**Comment by TizianoDeMatteis** [comment]
Hi @gabrielrodcanal,

in DaCe we currently offer a simple [method](https://spcldace.readthedocs.io/en/latest/source/dace.transformation.auto.html#dace.transformation.auto.fpga.fpga_rr_interleave_containers_to_banks) to allocate in a round-robin fashion the memory buffers on the available off-chip memory banks. 

With the latest pull request (#1352) we extended it to support also HBM and not just DDR (as in the previous version).

For your use case, you can apply it as follows:

```
sdfg.apply_transformations(FPGATransformSDFG) # same as before

from dace.transformation.auto import auto_optimize, fpga
fpga.fpga_rr_interleave_containers_to_banks(sdfg, memory_type="HBM")

sdfg(u=u, v=v) # same as before
```

In this way, the two memory buffers are allocated into two distinct HBM banks.

Let us know if this solves your issue

**Comment by gabrielrodcanal** [comment]
Hi @TizianoDeMatteis,
Yes, this solves the issue. Thank you.

**Comment by gabrielrodcanal** [comment]
Hi @TizianoDeMatteis,
Yes, this solves the issue. Thank you.
