### ISSUE TITLE
Submodule `cub` (`github.com/NVlabs/cub.git`) no longer work.

### ISSUE THREAD

**Issue by philip-paul-mueller** [spcl/dace#1414]
The reason for this is that they have removed the branch `1.8.0` that `.gitmodule` is referring to. However, there is the tag `v1.8.0` (`c3cceac115c072fb63df1836ff46d8c60d9eb304`). But `git-submodule` or rather the `-b` flag is only able to [follow branches and not tags](https://stackoverflow.com/questions/1777854/how-can-i-specify-a-branch-tag-when-adding-a-git-submodule) which this is not a problem per se, it is inconvenient.

I think the simplest thing to do is fork the repo and then creating a branch.

**Comment by tbennun** [comment]
Since nvlabs/cub is now archived, we can reset the commit hash to a specific one. One of the problems when we did that is that they force-pushed at some point and all the commit hashes changed (historically too).
