### ISSUE TITLE
Frontend seems to remove scalar transients 

### ISSUE THREAD

**Issue by philip-paul-mueller** [spcl/dace#1422]
I discovered the bug while I was working on issue #1389. Let's considering the following code, which, as it is, fails, to be precise it will fail to compile with the message that variable `d` is unknown.

```Python
import dace
import numpy as np

N = dace.symbol("N", dace.int32)

@dace.program
def filling(A: dace.float64[N, N], value: dace.float64):
    c = 0.3 + 1.0
    d = c + 1.5
    #A[0, 0] = d     # Uncomment either this line
    A.fill(d)
    #return d       # or this line to make the function work 
#

N,   value = 8,   0.3
input = np.ndarray((N, N)).astype(np.float64)
input_ref = np.copy(input)
input[:] = 0.0
input_ref[:] = value + 2.5

filling(input, value)
assert np.allclose(input, input_ref)    # Will fail
```

To "fix" the above program one has to uncomment at least one of the marked lines.

It is also interesting to look at the SDFG directly (not that `.to_sdfg()` does not apply any optimizations). This shows that the computations for generating `d` is omitted, which explains the above error. Enabling either of these lines will make `d` appear in the SDFG.

**Comment by alexnick83** [comment]
How does this fail to compile when `A.fill(d)` should raise an exception in the frontend (replacements.py)? The frontend doesn't remove any transients. Any changes can only be done in preprocessing or (more likely) by simplification (DeadDataflowEliminitation). Unless you changed your configuration, by default, `to_sdfg` will simplify. My guess is that your attempt to support data arguments for `fill` does not show `d` being used, Subsequently, DataFlowEliminitation removes it.

**Comment by philip-paul-mueller** [comment]
@alexnick83 you are right setting `simplify` to `False` keeps `d` in the graph.
Do you by chance know I can tell DaCe that `d` is being used, if not I will figuring it out myself.

And thanks a lot for the help/hint.

**Comment by alexnick83** [comment]
Generally, DeadDataFlowElimination finds transients that are not read and removes their access nodes (applied recursively).

**Comment by philip-paul-mueller** [comment]
It turned out that the problem was that I forgot to add a memlet as seen in [this (abandoned commit)](https://github.com/spcl/dace/pull/1420/commits/35c72ccbd4f13682b8e9cbc3f670550414804d64].

@alexnick83 Thanks again for the hint.
