### ISSUE TITLE
Deepcopy of state in _copy_state copies the parent sdfg

### ISSUE THREAD

**Issue by luigifusco** [spcl/dace#1443]
https://github.com/spcl/dace/blob/4139ddf02a2c274d583f1d99604cb6e03d656089/dace/transformation/helpers.py#L206-L208

The state is deepcopied and inserted into the sdfg. This results in an expensive copy of the state._parent sdfg, and in potential failures of the state validation (that checks that all states in an sdfg have that sdfg instance as parent).

In general, using deepcopies instead of dedicated methods sounds dangerous.

**Comment by alexnick83** [comment]
Can you verify that it is indeed deep-copying the parent SDFG? In general, when making a clone of an object of some DaCe class, we do deep-copy, but we also describe what deep-copy should do in the class's `__deepcopy__` method. It makes sense to me that deep-copying an SDFGState should not copy the parent SDFG but rather make a reference to the original parent SDFG. Therefore, the bug should be in `SDFGState.__deepcopy__`. See also [here](https://docs.python.org/3/library/copy.html).

**Comment by luigifusco** [comment]
```
@dace.program
def double_loop(arr: dace.float32[N]):
    for i in range(N):
        arr[i] *= 2
    for i in range(N):
        arr[i] *= 2

sdfg = double_loop.to_sdfg()
from dace.transformation.helpers import find_sdfg_control_flow
from dace.sdfg.validation import validate_sdfg
find_sdfg_control_flow(sdfg)
validate_sdfg(sdfg)
```

is enough to trigger the error. The _parent of teh copy and the sdfg are two different instances on comparison, while the original uncopied state is valid

**Comment by tbennun** [comment]
The bug was indeed in `SDFGState.__deepcopy__`. For safety (and in the same way that we implement SDFG's deepcopy), I now set the parent to None if you copy an orphaned state in #1446. This ensures we don't make any mistakes.
