### ISSUE TITLE
GPU allocation failure

### ISSUE THREAD

**Issue by philip-paul-mueller** [spcl/dace#1500]
During my experiments with an ICON stencil (on a larger grid) I encountered the `cudaErrorIllegalAddress` (700) with the description "an illegal memory access was encountered".

Long story short, because of "reasons"^{(R)} there are a lot of allocations of very small arrays in a GPU kernel.
Since, as far as I can tell, the kernel code is (partially) generated by the CPU code generator, the memory allocation uses an unchecked call to `operator new[]`.
On the CPU this is fine, because the standard says that if the operator fails a `bad_alloc` exception is generated (there is a form which allows to return `NULL`).
As it turns out if `operator new[]` fails inside a kernel it always returns `NULL`.
The only thing of documentation I found for this was [this post](https://forums.developer.nvidia.com/t/new-operator-in-device-functions/50150), which implies this behaviour (I wrote a program to verify this).

The error is partially based in our less than optimal translation from ITIR to SDFG.
While I agree we should fix gt4Py regarding this, we should also update the code generator to issue a guard, to get an error.

**Comment by tbennun** [comment]
First, mallocs in GPU kernels are technically allowed (as you said, they go on the heap).

Unless the storage location was set to Default, the problem is not in dace itself but in the component that creates the SDFG. If the IR specifies GPU_Global, the memory will be allocated outside the kernel. If using the heap is done on purpose, then this is treated as a runtime error for all intents and purposes and you will get that information back to Python via the GPU error checks. I’d recommend fixing the root cause in the frontend.

**Comment by philip-paul-mueller** [comment]
I fully agree with you. I already identified the the root cause and currently think about how to fix it.
I just think that if an allocation fails one should get an error _immediately_ not some time later, as suggested by [Eric Raymond](https://en.wikipedia.org/wiki/Unix_philosophy#Eric_Raymond's_17_Unix_Rules).

Furthermore, the error is not something like "memory exhausted" or "allocation failed" that is specific and/or useful, but instead was `cudaErrorIllegalAddress`  which does not tell you that much and could be anything.

I would think that it would be worth the effort.

**Comment by BenWeber42** [comment]
If I understand this correctly, the status quo is (as Tal explained):

> If using the heap is done on purpose, then this is treated as a runtime error for all intents and purposes and you will get that information back to Python via the GPU error checks.

So DaCe will report the `cudaErrorIllegalAddress` (700) to the user. Unfortunately, this error is not very descriptive of what actually went wrong. 

From: https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038
> The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistent state and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunched.

Causes for this error can include:
* Dereferencing a null pointer,
* Dereferencing an invalid address (outside allocated memory)
* Dereferencing a pointer with invalid alignment

I have seen this error 700 many times and, I believe, it's pretty much the equivalent of a segfault on CPUs which is neither very descriptive (segfaults are mostly just any kind of memory errors).

However, I think the big issue in making this more descriptive or failing earlier is the implementation. And in particular, how to implement this without sacrificing performance. I think essentially you would have to add checks to each `new` and exit early (and somehow report to the host which `new` failed). Adding such checks can have at least two negative effects on performance:
1) Thread divergence
2) Inhibiting instruction scheduling for the compiler

Especially (2) worries me the most. The streaming multiprocessors of GPUs are highly asynchronous machines, and `nvcc` will try hard to schedule instructions to maximize performance (e.g., increase ILP, order for better cache utilization). Such a check and early exit sounds like a hard barrier for instruction scheduling. I don't see a way to add these checks that won't negatively affect performance (I have seen this happen for `for` loops with `continue` statements).

Alternatively, such checks could be added in some sort of _debugging_ mode. But I think the case of a debugging mode to detect errors in the SDFG sounds quite niche. I just don't think this case is important enough right now to prioritize.

To progress with this issue, I think we would need to discuss a specific solution and see if we can find the resources to implement this. But I am skeptical that either part is worth it at this stage.

**Comment by philip-paul-mueller** [comment]
Hello Ben,
I think you are right, an exit might not be the right thing to do, maybe just printing out a message?
I also see that this should only issued in some kind of debug mode.
However, I also see that it would have rather limited effect.

Best, Philip
