### ISSUE TITLE
"Returning" Views Fails 

### ISSUE THREAD

**Issue by philip-paul-mueller** [spcl/dace#1519]
Returning a view is not a good idea, but looking at this SDFG:
![2024-02-15-162315_2556x1385_scrot](https://github.com/spcl/dace/assets/147368808/68930ed9-d1c0-4c53-bb82-f5f1e98ab8fa)

I would expect that DaCe generates code that performs the copy from `c` into `__return`, but this is not the case.
[failing_sdfg.json](https://github.com/spcl/dace/files/14298751/failing_sdfg.json)

**Comment by tbennun** [comment]
Is this from a specific frontend? When connecting a view, the original data container must always be there for the dataflow analysis. See https://spcldace.readthedocs.io/en/latest/sdfg/ir.html#views-and-references for more information.

**Comment by philip-paul-mueller** [comment]
No I have build it on my own.

If I understand you correctly it would work if the `Return_State` contained something like `c -> d -> __return`?

In my Jax to SDFG translator I translate every Jax equation into its own state, therefore a View always created in a different state than it is used, thus this can not work.
A solution could be to directly write into another Array and hope that DaCe will fuse the states and remove the Array and maintains the View.

Thanks in advance for your time and support.

@tbennun

**Comment by alexnick83** [comment]
I am unsure if this helps, but on the Python frontend, we do the same as you and keep a dictionary/mapping of the views to the underlying data. Then, when finishing parsing, we add the necessary access nodes and edges/memlets. See https://github.com/spcl/dace/blob/47ef29ae0d88cee28076b6658a5cf24d57166a80/dace/frontend/python/newast.py#L1300

**Comment by philip-paul-mueller** [comment]
@alexnick83 
Thanks you, it is actually helpful, I was thinking about if I should do something along these lines too, but was unsure if it would be a good approach.
