### ISSUE TITLE
Compile multiple SDFGs with the same name

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#152]
**Describe the bug**
If two different SDFG are loaded inside the same .py or .ibynb script with the same name
```
sdfg1 = dace.SDFG('unique_name')
x = sdfg1.compile(optimizer=False)
sdfg2 = dace.SDFG('unique_name')
y = sdfg2.compile(optimizer=False)
``` 

An error appears:
```
... dace/codegen/compiler.py:104: UserWarning: Library ... already loaded, renaming file self._library_filename)
Segmentation fault (core dumped)
```

**Reproduce**
Sometimes it is required to make more than two SDFG with the same name to reproduce.

**Comment by definelicht** [comment]
@am-ivanov @tbennun I think this been fixed in the meantime? Could you run the example again to verify?

**Comment by tbennun** [comment]
works for me, not sure about the situation for the setup of @am-ivanov .
