### ISSUE TITLE
state.topological_sort is incorrect, while sdfg.utils.dfs_topological_sort is correct

### ISSUE THREAD

**Issue by ThrudPrimrose** [spcl/dace#1560]
**Describe the bug**
When I call:
`dace.sdfg.utils.dfs_topological_sort(state)`
I have a correct topological sorting of nodes within a state but, calling:
`state.topological_sort()`
Results with an ordering that is not correct.

**To Reproduce**
I have a minimal program to reproduce the issue. In the example I reproduce, an access node, which has an edge to an map node, is listed after the map when sorted with `state.topological_sort`

**Expected behavior**
When I print the nodes and edges in the order received from the nodes and their outgoing edges are printed as follows:

```
...
dataA  |  [dataA:None  -(gpu_dataA[0:N] <- [0:N])->  gpu_dataA:None]
kernelAddBToAOnGPUNoWCR_42[i=0:N]  |  [kernelAddBToAOnGPUNoWCR_42[i=0:N]:OUT_dataA  -(gpu_dataA[0:N])->  gpu_dataA:None]
gpu_dataA  |  [gpu_dataA:None  -(gpu_dataA[0:N])->  kernelAddBToAOnGPUNoWCR_42[i=0:N]:IN_dataA]
gpu_dataA  |  [gpu_dataA:None  -(dataA[0:N] <- [0:N])->  dataA:None]
dataA  |  []
```

Expected would be: (the access node gpu_dataA that as outgoing edge to the kernel, needs to be before the kernel)
```
gpu_dataA  |  [gpu_dataA:None  -(gpu_dataA[0:N])->  kernelAddBToAOnGPUNoWCR_42[i=0:N]:IN_dataA]
gpu_dataB  |  [gpu_dataB:None  -(gpu_dataB[0:N])->  kernelAddBToAOnGPUNoWCR_42[i=0:N]:IN_dataB]
kernelAddBToAOnGPUNoWCR_42[i=0:N]  |  [kernelAddBToAOnGPUNoWCR_42[i=0:N]:OUT_dataB  -(gpu_dataB[i])->  _Mult_:__in2, kernelAddBToAOnGPUNoWCR_42[i=0:N]:OUT_dataA  -(gpu_dataA[i])->  _Add_:__in2]
_Mult_  |  [_Mult_:__out  -(__tmp10[0])->  __tmp10:None]
__tmp10  |  [__tmp10:None  -(__tmp10[0])->  _Add_:__in1]
_Add_  |  [_Add_:__out  -(__tmp11[0])->  __tmp11:None]
__tmp11  |  [__tmp11:None  -(__tmp11[0])->  assign_43_8:__inp]
assign_43_8  |  [assign_43_8:__out  -(gpu_dataA[i])->  kernelAddBToAOnGPUNoWCR_42[i=0:N]:IN_dataA]
kernelAddBToAOnGPUNoWCR_42[i=0:N]  |  [kernelAddBToAOnGPUNoWCR_42[i=0:N]:OUT_dataA  -(gpu_dataA[0:N])->  gpu_dataA:None]
gpu_dataA  |  [gpu_dataA:None  -(dataA[0:N] <- [0:N])->  dataA:None]
dataA  |  []
```

The generated example program I can't attach but here is the full code, it prints the nodes and saves the sdfg as ex.sdfg:
```
import dace
import numpy as np
import cupy as cp
from dace.dtypes import StorageType, ScheduleType
from dace.sdfg.analysis import cfg

size = int(1e4)
N = dace.symbol('N')

@dace.program
def kernelInitAOnGPU(dataA : dace.float32[N] @ StorageType.GPU_Global):
    for i in dace.map[0:N] @ ScheduleType.GPU_Device:
        dataA[i] = 2.0

@dace.program
def kernelInitBOnGPU(dataB : dace.float32[N] @ StorageType.GPU_Global):
    for i in dace.map[0:N] @ ScheduleType.GPU_Device:
        dataB[i] = 0.65

@dace.program
def copyToGPU(data : dace.float32[N] @ StorageType.Default):
    # Does not compile if: gpu_data : dace.float32[N] @ StorageType.GPU_Global = cp.array(data)
    gpu_data : dace.float32[N] @ StorageType.GPU_Global = cp.zeros((N,), dace.float32)
    gpu_data[0:N] = data[0:N]
    return gpu_data


@dace.program
def kernelOverwriteBAddBToAOnGPUNoWCR(
    dataA : dace.float32[N] @ StorageType.GPU_Global,
    dataB : dace.float32[N] @ StorageType.GPU_Global
    ):
    for i in dace.map[0:N] @ ScheduleType.GPU_Device:
        dataB[i] = 3.0
        dataA[i] = 0.5 * dataB[i] + dataA[i]

@dace.program
def kernelAddBToAOnGPUNoWCR(
    dataA : dace.float32[N] @ StorageType.GPU_Global,
    dataB : dace.float32[N] @ StorageType.GPU_Global
    ):
    for i in dace.map[0:N] @ ScheduleType.GPU_Device:
        dataA[i] = 0.5 * dataB[i] + dataA[i]

@dace.program
def kernelAddBToAOnCPU(
    dataA : dace.float32[N] @ StorageType.Default,
    dataB : dace.float32[N] @ StorageType.Default
    ):
    for i in dace.map[0:N] @ ScheduleType.CPU_Multicore:
        dataA[i] += 0.5 * dataB[i]

@dace.program
def kernelLifetimesOnGPUNoWCR(dataA : dace.float32[N] @ StorageType.Default,
                       dataB : dace.float32[N] @ StorageType.Default):
    gpu_dataA = copyToGPU(data = dataA)
    gpu_dataB = copyToGPU(data = dataB)
    kernelInitAOnGPU(dataA = gpu_dataA)
    kernelInitBOnGPU(dataB = gpu_dataB)
    kernelOverwriteBAddBToAOnGPUNoWCR(dataA = gpu_dataA, dataB = gpu_dataB)
    dataA[0:N] = gpu_dataA[0:N]
    dataB[0:N] = gpu_dataB[0:N]
    kernelAddBToAOnCPU(dataA = dataA, dataB = dataB)
    gpu_dataA[0:N] = dataA[0:N]
    gpu_dataB[0:N] = dataB[0:N]
    kernelAddBToAOnGPUNoWCR(dataA = gpu_dataA, dataB = gpu_dataB)
    dataA[0:N] = gpu_dataA[0:N]

def testLifetimesOnGPUNoWCR():
    dataA = np.zeros(size, dtype=np.float32)
    dataB = np.zeros(size, dtype=np.float32)
    reference = np.full(size, 6.5, dtype=np.float32)
    sdfg = kernelLifetimesOnGPUNoWCR.to_sdfg(dataA=dataA, dataB=dataB, N = size)
    sdfg.save("ex.sdfg")
    state_order = list(cfg.stateorder_topological_sort(sdfg))

    for state in state_order:
        nodes_with_0_incoming = list()
        for nd in state.nodes():
            if state.in_degree(nd) == 0:
                nodes_with_0_incoming.append(nd)

        if len(nodes_with_0_incoming) == 1:
            topologically_sorted_nodes1 = list(dace.sdfg.utils.dfs_topological_sort(state))
            topologically_sorted_nodes2 = list(state.topological_sort(nodes_with_0_incoming[0]))
            def same_element_representation(list1, list2):
                # Check if the lists have the same length
                if len(list1) != len(list2):
                    return False

                # Convert each element to string and compare
                for elem1, elem2 in zip(list1, list2):
                    if str(elem1) != str(elem2):
                        return False

                return True
            if not same_element_representation(topologically_sorted_nodes1, topologically_sorted_nodes2):
                print(f"For state {state}:")
                print("DaCe SDFG Utils DFS Topological Sort:")
                for n in topologically_sorted_nodes1:
                    print(n, " | ", state.out_edges(n))
                print("===")
                print("State's Internal Topological Sort:")
                for n in topologically_sorted_nodes2:
                    print(n, " | ", state.out_edges(n))
                print("Not equal")
                print("***")

    sdfg(dataA = dataA, dataB = dataB, N=size)
    assert(np.allclose(dataA, reference))

if __name__ == '__main__':
    testLifetimesOnGPUNoWCR()
```

**Desktop (please complete the following information):**
 - I am on Ubuntu 23.10
 - Output of git log: commit 78759b56b537930a5fd3d4bdd64048960765adf1 (HEAD -> master, tag: v0.16rc1)

**Comment by BenWeber42** [comment]
Yes, this seems to be a bug in `Graph.topological_sort` of our own _graph layer_:
https://github.com/spcl/dace/blob/ee5a6dfe695f329c3882105b087f3563a0c80b81/dace/sdfg/graph.py#L367-L390

This algorithm can fail for a graph like:
```console

 A
 | \
 |   \
 v    v 
 B <- C
```
The only correct topological order would be A, C, B. Whereas the current algorithm can also produce the incorrect order of A, B, C (ignoring the dependency between B and C).

My language server could find only three references to the broken `Graph.topological_sort` function, and all three seem to be for `SDFG`/`ControlFlowRegion`.

I would suggest completely removing `Graph.topological_sort` and replacing all occurrences with the working `utils.dfs_topological_sort`.

However... makes no sense to use `topological_sort` for `SDFG`/`ControlFlowRegion`, they can be cyclic. Why are we trying to get a topological order for a potentially cyclic graph?! Probably we are looking for a different kind of ordering :thinking:

The references that my language server found:

https://github.com/spcl/dace/blob/ee5a6dfe695f329c3882105b087f3563a0c80b81/dace/codegen/targets/framecode.py#L534-L570
https://github.com/spcl/dace/blob/ee5a6dfe695f329c3882105b087f3563a0c80b81/dace/sdfg/state.py#L2548-L2605
https://github.com/spcl/dace/blob/ee5a6dfe695f329c3882105b087f3563a0c80b81/dace/transformation/passes/constant_propagation.py#L156-L242

**Comment by BenWeber42** [comment]
I put some thought into this:

There are two kinds of issues at play here:

1. `state.topological_sort` naming is misleading, because it is returns breadth-first-search order of nodes, while the naming implies it returns a topological order of nodes.
2. There are various call-sites that try to get a topological order of nodes for potentially cyclic graphs. Even though they are _affected_ by (1), they are still separate issues, because it is erroneous to try to get a topological order of a potentially cyclic graph.

I think we should separate (1) and (2). Specifically, this issue should be about (1) whereas (2) should be separate issues.

Going forward with (1):

I think the function should be renamed from `topological_sort` to `bfs_nodes`. Interestingly, neither `networkx` nor our own graph layer (`dace/sdfg/graph.py`) has a method to get a bfs order of nodes. `networkx` provides `bfs_edges` which can be used to easily get a bfs order of nodes. This is explained in their second example here: https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.traversal.breadth_first_search.bfs_edges.html#bfs-edges

I think it makes sense that our own graph layer provides this helper functionality. I.e., renaming `topological_sort` fixes (1) while also introducing a useful helper functionality that doesn't exist elsewhere currently.

We could also consider replacing some of the implementation of the current `topological_sort` by reusing `networkx.bfs_edges`.

**Comment by BenWeber42** [comment]
Very nice! Then it looks like we are on a good track when it comes to the second kind of issue mentioned above (i.e., (2)).

I am currently investigating a fix for (1) in https://github.com/spcl/dace/pull/1590

Let's see how these develop. Likely, the two current PRs will lead to merge conflicts, but it currently looks like we can fix them easily.
