### ISSUE TITLE
SDFG class documentation does not match implementation

### ISSUE THREAD

**Issue by tim0s** [spcl/dace#1563]
The SDFG class init method looks like this:

```
def __init__(self,
                 name: str,
                 constants: Dict[str, Tuple[dt.Data, Any]] = None,
                 propagate: bool = True,
                 parent=None):
        """ Constructs a new SDFG.

            :param name: Name for the SDFG (also used as the filename for
                         the compiled shared library).
            :param symbols: Additional dictionary of symbol names -> types that the SDFG
                            defines, apart from symbolic data sizes.
            :param propagate: If False, disables automatic propagation of
                              memlet subsets from scopes outwards. Saves
                              processing time but disallows certain
                              transformations.
            :param parent: The parent SDFG or SDFG state (for nested SDFGs).
        """
```

Note that the second argument is named ```constants``` in the implementation but ```symbols``` in the documentation.
I don't want to just change it because I don't fully understand what is meant here and for me the semantics are different: Constants do not change within their scope of definition, Symbols (as an SDFG concept) can be changed i.e., on interstate edges AFAIU.

**Comment by alexnick83** [comment]
The documentation is wrong. It should be constants. Symbols are added to SDFGs as follows:
- Explicitly: call `SDFG.add_symbol` (please note that direct manipulation of the `SDFG.symbols` dictionary is also allowed)
- Implicitly: whenever you add any elements on the SDFG that depend on/refer to specific symbols. For example, in the following code snippet, `N` will be implicitly added to the SDFG and the output should be `{'N': int}`:
```python
import dace
N = dace.symbol('N')
sdfg = dace.SDFG('implicit_symbol_test')
sdfg.add_array('A', shape=(N,), dtype=dace.int32)
print(sdfg.symbols)
```

I will make a PR.

**Comment by tim0s** [comment]
Fixed by https://github.com/spcl/dace/pull/1571
