### ISSUE TITLE
GPU Code Generation Fails Because of  `CopyToMap`

### ISSUE THREAD

**Issue by philip-paul-mueller** [spcl/dace#1674]
The CUDA code generation will call `CopyToMap` for certain memlets.
However, it seems that there is an error in certain cases.

We start with the initial SDFG.
It writes the result back in a state:
![initial_copy](https://github.com/user-attachments/assets/b6ad4614-e488-49f7-b92a-79800b686aa7)

If we try to compile the initial SDFG, attached as `initial_sdfg.json`, code gen will generate the code but the compilation will fail, with the error that `__vn_size_1` is not specified.
The output folder contains a copy of the SDFG (`program.sdfg`); Attached as `transformed_sdfg.json`.
We can visualize it and see that the memlet for writting back the result has been turned into a map.
![after_transformation](https://github.com/user-attachments/assets/8feba93d-2fad-4935-9cf9-7a040505e2da)

What is now very interesting if we load the transformed SDFG we can compile it without issues.

[initial_sdfg.json](https://github.com/user-attachments/files/17276111/initial_sdfg.json)
[transformed_sdfg.json](https://github.com/user-attachments/files/17276106/transformed_sdfg.json)

**Comment by tbennun** [comment]
@philip-paul-mueller can we close this now that #1675 is merged? Please reopen if not
