### ISSUE TITLE
Scalar to symbol promotion fails if scalar is read in another state

### ISSUE THREAD

**Issue by romanc** [spcl/dace#1727]
**Describe the bug**

In the attached (see below) generated SDFG, I have the following pattern (see screenshot below)

- State 1: Evaluate (boolean) condition inside a Tasklet, write the condition to a transient scalar.
- State 2: Read generated transient scalar into another transient boolean that is manually promoted to a symbol.
- State 3 (onwards): The symbol is now used for `if` / `else` branching.

This triggers scalar to symbol promotion on the evaluation scalar `maks_*` as well as on the intermediate boolean `if_expression_*`. It looks like `mask_*` is processed twice (once per state) and scalar to symbol promotion then fails when `mask_*` is processed in the second state (again).

**To Reproduce**

1. Load the attached (see below) SDFG (`original-generated.sdfg`)
2. Run `simplify()` on that SDFG
3. See error `networkx.exception.NetworkXError: nbunch is not a node or a sequence of nodes`

**Expected behavior**

I expect scalar to symbol pass to fail gracefully in case it can't promote a scalar.

**Screenshots**

![image](https://github.com/user-attachments/assets/272ed702-d571-47d6-9184-f4ebebc97175)

**Desktop (please complete the following information):**

 - OS: Linux (OpenSUSE)
 - Dace version: rev 945b5ce4ad26ba9047467d95e75e9aec48792506

**Additional context**

Zip file with SDFGs [scalar-to-symbol.zip](https://github.com/user-attachments/files/17617115/scalar-to-symbol.zip) contains:

- original generated SDFG
- SDFG right before scalar to symbol pass
- SDFG after scalar to symbol pass failed

Quickfix in https://github.com/spcl/dace/compare/main...romanc:romanc/scalar-to-symbol seems to work in my simple test case. However, not sure about this approach. I might just be treating symptoms without understanding the problem.

Last part of the stack trace, tracing the problem back to 

![image](https://github.com/user-attachments/assets/4f2b6900-3227-4ac4-8416-72c1d465492f)

I search the open issues and found https://github.com/spcl/dace/issues/1129 and https://github.com/spcl/dace/issues/1665 which might be related.

**Comment by phschaad** [comment]
Scratch that, the quickfix does not get close to passing the tests. We need to investigate this further.

**Comment by romanc** [comment]
Thanks for looking into this issue.

**Comment by tbennun** [comment]
What is a SymbolRef? I don't think that's a supported object, as the function expects a set of strings. Who is creating that?
