### ISSUE TITLE
FPGA: after Map Tiling transformation, loops  `auto` are generated

### ISSUE THREAD

**Issue by TizianoDeMatteis** [spcl/dace#184]
**Describe the bug**
After that a Map Tiling transformation has been applied, the code generator produces loops with `auto` variable, which are bad for Intel Fpga

**To Reproduce**

Take a simple example with a map (like dot), this occurs:
- if SDFG has been transformed for FPGA and then Map Tiling is applied
- if Map Tiling is applied and then the SDFG is transformed for FPGA

**Expected behavior**
Do not produce loops with `auto` variables

**Comment by definelicht** [comment]
@TizianoDeMatteis Was this fixed?

**Comment by TizianoDeMatteis** [comment]
@definelicht 
Yes, fixed with #187.
Closing.
