### ISSUE TITLE
Codegen for nested SDFG with vectorization

### ISSUE THREAD

**Issue by manuelburger** [spcl/dace#190]
In the attached code we have a nested SDFG with vectorized memlets of width `w` going from the outer SDFG into the inner one. In the inner one we use again the same `w` to access memory. This produces code that does not compile for `CPU`. As the inner code expects a simple pointer to memory but receives a vector  @tbennun @definelicht 

Code: [vectorizationNestedSDFG.zip](https://github.com/spcl/dace/files/4403860/vectorizationNestedSDFG.zip)

Graph for reference: [Graph](https://spcl.github.io/dace/sdfv.html?url=https://raw.githubusercontent.com/manuelburger/daceGraphs/master/vecAddNested.sdfg)

**Comment by tbennun** [comment]
You can also embed the SDFG [directly](https://spcl.github.io/dace/sdfv.html?url=https://github.com/spcl/dace/files/4403921/program.sdfg.txt)

**Comment by tbennun** [comment]
This is fixed with the new API (#301). I even made a test from your file called `nested_vector_type_test.py`.

Thanks!
