### ISSUE TITLE
Python Frontend: literals aren't converted in tasklets

### ISSUE THREAD

**Issue by orausch** [spcl/dace#195]
**Describe the bug**
Python literals aren't converted when translated to C++. The following code produces a compiler error. Although this is fixable in this case by replacing `0-> 0.0`, this doesn't work when the array types are `float32` because `0.0f` is invalid in python.

```python
import dace
import numpy as np

@dace.program
def max_prog(A: dace.float64[1], B: dace.float64[1]):
    with dace.tasklet:
        a << A[0]
        b >> B[0]
        
        b = max(a, 0)

max_prog.to_sdfg()


A = np.ones((1,), dtype=np.float64)
B = np.zeros((1,), dtype=np.float64)

max_prog(A=A, B=B)
```
**Expected behavior**
Maybe the type of the literal is inferred from the signature of max, and the first arg?

**Comment by alexnick83** [comment]
This is not a bug. You must use literals of the correct type (although I don't really understand why the C++ compiler doesn't just do the conversion in this case). You can use any dace (numpy) type. For 32-bit float you should use `dace.float32(0)`.

**Comment by orausch** [comment]
Right, that works, thanks!
