### ISSUE TITLE
Nested SDFG on FPGA with WCR

### ISSUE THREAD

**Issue by manuelburger** [spcl/dace#197]
Nested SDFGs on FPGA using a conflict resolution result in a `KeyError` such as the following:
```
Traceback (most recent call last):
  File "dotNestedSDFG_example.py", line 126, in <module>
    match.apply(test_sdfg)   
  File "/home/manuel/.local/lib/python3.7/site-packages/dace/transformation/interstate/fpga_transform_sdfg.py", line 53, in apply
    fpga_transform.apply(sdfg)
  File "/home/manuel/.local/lib/python3.7/site-packages/dace/transformation/interstate/fpga_transform_state.py", line 166, in apply
    or not isinstance(node.desc(sdfg), dace.data.Array)):
  File "/home/manuel/.local/lib/python3.7/site-packages/dace/graph/nodes.py", line 230, in desc
    return sdfg.arrays[self.data]
KeyError: '__z1_out'
```
The same code works fine on CPU.

Here the graph for reference: [Graph](https://spcl.github.io/dace/sdfv.html?url=https://raw.githubusercontent.com/manuelburger/daceGraphs/master/dotProductNested_example.sdfg)

Here a sample code, which reproduces the error: 
[dotNestedSDFG_example.zip](https://github.com/spcl/dace/files/4419331/dotNestedSDFG_example.zip)

**Comment by definelicht** [comment]
@tbennun @alexnick83 Do you know what could have broken this?

**Comment by tbennun** [comment]
@definelicht This has probably always been an issue with nested SDFGs in nested SDFGs, since you loop over `all_nodes_recursive` and then assume that the parent SDFG is always the top SDFG, see the code:

```python
        for node, graph in state.all_nodes_recursive():
            # ...
                                    # This must be copied to device
                                    input_nodes.append(parent_edges.dst)
                                    wcr_input_nodes.add(parent_edges.dst)

        if input_nodes:
            # ...
            for node in input_nodes:
                if (not isinstance(node, dace.graph.nodes.AccessNode)
                        or not isinstance(node.desc(sdfg), dace.data.Array)):
```

**Comment by definelicht** [comment]
@manuelburger This has been merged

**Comment by manuelburger** [comment]
Issue comes up again in more complex graphs, than the previous example. Here is another graph making problems.

[test_dot.zip](https://github.com/spcl/dace/files/4461685/test_dot.zip)

**Comment by definelicht** [comment]
Different problem now, but I will investigate :-)

**Comment by definelicht** [comment]
Fixed (hopefully) with `ArrayInterface` removal/revamp.
