### ISSUE TITLE
Intel FPGA memory conversion to scalar in WCR

### ISSUE THREAD

**Issue by manuelburger** [spcl/dace#223]
The attached graph has a memory buffer `_xRowResPartial_chunk` in a nested SDFG. The nested SDFG is executed multiple times and the results are accumulated via WCR in the buffer. For `intel_fpga`, if this buffer has size 1, it is converted to a scalar, thus not keeping results from previous iterations.

See graph [here](https://spcl.github.io/dace/sdfv.html?url=https://raw.githubusercontent.com/manuelburger/daceGraphs/master/trsvSDFG_scalerConversionIssue.sdfg)

Download graph:
[trsvSDFG_scalerConversionIssue.zip](https://github.com/spcl/dace/files/4540122/trsvSDFG_scalerConversionIssue.zip)

**Comment by definelicht** [comment]
@tbennun I think this might go away with the upcoming codegen changes?

**Comment by tbennun** [comment]
looks like it, yes

**Comment by tbennun** [comment]
@manuelburger in #298 we add support to set the output connector to always be a pointer (`add_tasklet`/`add_nested_sdfg` now also accept a dictionary for inputs and outputs, which you can use to set the local variable to `dace.pointer(dace.float32)` or any other type). Once this is merged, it should work right after setting the output connector type of the SDFG.
