### ISSUE TITLE
Substitute abs with fabs?

### ISSUE THREAD

**Issue by definelicht** [spcl/dace#232]
For Intel FPGA, `abs` cannot be used on floating point variables, and `fabs` must be called explicitly. This sucks.

Perhaps we want to replace `abs` with `fabs` if we see that it's used on a floating point type?

**Comment by definelicht** [comment]
@TizianoDeMatteis What do you think?

**Comment by TizianoDeMatteis** [comment]
Sounds good to me...but where? OpenCLKeywordRemover?

**Comment by definelicht** [comment]
Of course :-)

**Comment by definelicht** [comment]
@TizianoDeMatteis this depends on #237, since we need to know that the expression in the function is a float. Gogo!
