### ISSUE TITLE
Shift register abstraction in DaCe

### ISSUE THREAD

**Issue by definelicht** [spcl/dace#243]
Shift registers are ubiquitous in Intel FPGA OpenCL code, used for anything from implementing stencil buffering to forcing the compiler to understanding a false dependency.

We should have an abstraction for this in DaCe, using the `hlslib::ShiftRegister` class for Xilinx, which achieves similar semantics. This will be a useful shorthand for many FPGA SDFGs.

Shift register semantics:
- New elements are always written at the front of the register, and can only be written at one location in the program.
- Every write causes all internal data to be shifted by one.
- Reads from the array can only happen at constant offsets ("taps" in Intel lingo).

**Comment by definelicht** [comment]
@TizianoDeMatteis Can you think of cases not covered by the semantics above? E.g., do we ever have multiple writes to the same shift register?

**Comment by TizianoDeMatteis** [comment]
@definelicht 
You can have multiple writes in the same shift register in systolic arrays, for draining.
(I've seen the same also in an FFT example but I'm not able to able to find it)

**Comment by definelicht** [comment]
Ok, I will allow this for Intel, but the hlslib version doesn't support this IIRC
