### ISSUE TITLE
Extra assignment and transient upon function call

### ISSUE THREAD

**Issue by tbennun** [spcl/dace#270]
In the numpy frontend, the following code:
```python
@dace.program
def extra_assignment(a: dace.float64[1]):
    b = np.ndarray([1], dtype=np.float64)
    b[0] = math.exp(a)
```
creates the following SDFG:
![sdfg](https://user-images.githubusercontent.com/8348955/81982121-970d0c00-9631-11ea-91ec-54b2207c469b.png)

The extra tasklet and transient can be omitted.

**Comment by alexnick83** [comment]
Maybe we should add this case to one of the strict transformations that remove redundant arrays/copies?

**Comment by tbennun** [comment]
that would be nice. If assign was an access node instead, then RedundantArray would kick in anyway.

**Comment by alexnick83** [comment]
We can change to direct copy between access nodes. Can you think of any case where the tasklet implementation would be preferable?

**Comment by tbennun** [comment]
I can only think of setting a constant, but that is not handled in assign.
