### ISSUE TITLE
DuplicateDLLError in jupyter notebook

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#33]
**Describe the bug**
If the first run of dace program fails in jupyter notebook, the second run will complain that the shared library is already loaded. 

**To Reproduce**
Steps to reproduce the behavior (see screenshot):
1. In cell 3 make some mistake: for example, forget arguments `K` and `M` 
2. Try to execute cell 4

**Expected behavior**
Cell 4 should be executed without any problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/9387186/68866310-7d2b5480-06f4-11ea-8f40-5e3f93ee7869.png)

**Comment by am-ivanov** [comment]
Probably related: #10

**Comment by tbennun** [comment]
Fixed
