### ISSUE TITLE
Support passing Pytorch tensors to SDFGs

### ISSUE THREAD

**Issue by orausch** [spcl/dace#359]
AFAIK @Shigangli already implemented this in https://github.com/orausch/dace/pull/1/commits/6d9c89d291d4441a000ed4f0389ea1fa9ea7e4f0, it would need to be ported over since we created the daceml repository

**Comment by tbennun** [comment]
I already committed it a while ago (935d7418020415a8e2a926d5c4e147411cde34dd). We are already using pytorch tensors in other projects. Is this not working for you?

**Comment by orausch** [comment]
Oh I didn't know that. Yup, it looks like it already works
