### ISSUE TITLE
SFDV: highlight memlet paths through nested SDFGs

### ISSUE THREAD

**Issue by orausch** [spcl/dace#388]
It would be useful if the memlet path could be highlighted through nested SDFG boundaries.

For example here the edge going from `ONNX_2_grad` to the nested SDFG could be highlighted.
![image](https://user-images.githubusercontent.com/22137236/95244854-b7bd4480-0812-11eb-8fc7-b98bed48e8db.png)

**Comment by tbennun** [comment]
Thanks for reporting, this is already a work in progress :)
