### ISSUE TITLE
Code style issue: too long functions

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#406]
**Python google styleguide**

> Prefer small and focused functions. If a function exceeds about 40 lines, think about whether it can be broken up without harming the structure of the program.

**Example**

https://github.com/spcl/dace/blob/6e91853c0f4fa06ebdd8672e52b478f9b7219873/dace/transformation/dataflow/map_fusion.py#L194

**Pros**

* More opportunities to reuse
* Easier to see what function does by reading called function names, without looking into the implementation of these functions

**Possible solution**

Split long functions into small functions across the boundaries defined by comments between chunks of block. 

**Before**
```
def foo():
  # do action X
  some code
  # do action Y
  some code
``` 

**After**
```
def do_action_X(...):
   some code
def do_action_Y(...):
   some code
def foo():
  do_action_X(...)
  do_action_Y(...)
```

**Comment by definelicht** [comment]
Agree, we did something like this for `unparse_tasklet`, for example. I would like to specifically mention `memlet_copy_to_absolute_strides` (in fact, after using it many times, I still don't _really_ understand what this function does).

**Comment by alexnick83** [comment]
I agree. This is a matter of identifying what methods would be suitable for replacing the original one. We can make a list of candidate methods and work on them when there is time.

**Comment by acalotoiu** [comment]
The difficulty is that this is hard to figure out in advance, and finding time is always a nightmare. Even though we all agree I suspect that unless we have some dedicated slot to do this stuff - something like a once every X months we spend 1-2 evenings on this, I am afraid this will always be pushed back by urgent stuff.
