### ISSUE TITLE
Code style issue: power features

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#407]
**Python google style guide**

> Avoid power features, use only when absolutely necessary.

https://google.github.io/styleguide/pyguide.html#219-power-features

**Examples**

* https://github.com/spcl/dace/blob/401254f076e5b55f6cb89a44d384a9e79076d810/dace/codegen/targets/cuda.py#L2051
* https://github.com/spcl/dace/blob/a3a1fb9b60d2414bb90a5837f83d30e4a0182b43/dace/properties.py#L367

**Cons**

* Difficult to find origins of class fields, functions, parameters. Requires reading the code.

**Possible solutions**

* Explicitly build lists of parameters (in a separate function) instead of extracting them with getattr().  

**Good use cases**

* Parse functions in python/numpy frontend

**Comment by tbennun** [comment]
In the first example we use the Python standard visitor pattern. This is used often in visitors that are non-intrusive (i.e., you don't want a `generate_cpu`, `generate_cuda`, and shove in your own implementation into the `Node` classes. This was considered in the past). Example from Python's AST visitor: https://github.com/python/cpython/blob/master/Lib/ast.py#L406

In the second example, that is only used in a convenience API as syntax sugar. The code does not rely on it and it was created at the behest of frustrated users who said Transformation API was too hard to use. This is one of the benefits of Python. Here is another use of the same feature in the popular PyTorch to keep neural-network module parameters: https://github.com/pytorch/pytorch/blob/f11f9a8c1f200c0798dd5043a958c563dfb00777/torch/nn/modules/module.py#L795
Feel free to propose a different API for transformation pattern subgraph nodes.

**Comment by alexnick83** [comment]
I will agree that the standard Python visitor pattern is horrible. I am pretty sure it is the reason that most (all?) people working on DaCe do not want to touch the code-generators with a 10-foot pole. But is there a better alternative proposal?

Is the second issue about the comprehensions? This is another "pythonic" thing that is not very intuitive unless you know how it works. Personally, I am using the comprehensions as long as it is something simple, e.g. sth if cond else something_else for sth in stuff. If it gets more complicated, it should be written with a for-loop (or moved to a function as suggested).
