### ISSUE TITLE
Code style issue: imports of classes and functions

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#410]
**Google style guide**

> Use import statements for packages and modules only, not for individual classes or functions.
https://google.github.io/styleguide/pyguide.html#22-imports

**Example**

https://github.com/spcl/dace/blob/v0.10.0/dace/transformation/dataflow/tiling.py#L6

**Comment by alexnick83** [comment]
I am somewhat indifferent to this. Two notes, though:
- Python language developers (and the developers of main Python modules) really use import like this. It is "pythonic." I am not sure why Google hates it (and why should we care)
- We already have a code-style of 80 chars per line. We may get very restricted if we have to add the module names all over the code.

**Comment by tbennun** [comment]
I agree with the code-length issue. 

As another note, we do strictly disallow in our (implicit) coding guidelines the use of: `from x.y.z import *` because that can be dangerous.
