### ISSUE TITLE
Code style issue: decorators

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#411]
**Google style guide**

> Use decorators judiciously when there is a clear advantage.
https://google.github.io/styleguide/pyguide.html#217-function-and-method-decorators

**Examples**

https://github.com/spcl/dace/blob/22fd2d20b896b58a39f5dedc698d0807296767a5/dace/transformation/transformation.py#L15
https://github.com/spcl/dace/blob/22fd2d20b896b58a39f5dedc698d0807296767a5/dace/transformation/dataflow/tiling.py#L12

**Cons**

Require to keep in mind that something will be made with class/function. Languages provide more classic features to support the registry, that people can understand faster.

**Possible solution**

Keep registry inside its own class. Define classmethod for this class, which creates an instance of the class and
fills it with default transformations. Such classmethod should import each transformation itself. The advantage of such design is that users can extend it by using its own class instance that is filled with user-provided transformations. Another advantage is that there is no global registry.

**Good uses**

To make annotations in python/numpy interface.

**Comment by tbennun** [comment]
I am undecided about this.

**Comment by definelicht** [comment]
Not sure I understand the possible solution. We need a global registry in any case (that's why it exists in the first place). Can you give a code example?

**Comment by am-ivanov** [comment]
@definelicht You can fill the registry manually by assigning each derived class to it (with a function call). It requires the same amount of code as writing decorator: one line for function call. To make base classes that "have a registry of derived classes", it is possible to inherit them from an interface that implements register/unregister methods.

**Comment by alexnick83** [comment]
Perhaps this should be merged with #407. The real issue here is that decorators are really a Python power feature that is unfortunately not intuitive unless you know what it does. I think that we are too invested in decorators to go back. Perhaps it would be simpler to write a short document where we explain what each decorator does?

**Comment by am-ivanov** [comment]
@alexnick83 I am raising the issue mostly to discuss adopting the guideline in the future code. It is not necessary to immediately rewrite all decorator occurrences. The current code can be gradually refactored on the case by case basis if we agree on it.

**Comment by tbennun** [comment]
@am-ivanov do you mean like this?

https://github.com/spcl/dace/blob/8551ce86ebae8262d16c4aa3384992825d93e876/dace/transformation/dataflow/mapreduce.py#L488

(from 9 months ago)

**Comment by am-ivanov** [comment]
@tbennun Yes, I meant this. Is it ugly or not is a matter of personal preferences. I also think that it is a bit uglier than the decorator approach. However, it is definitely better in terms of readability: you immediately see what code is executed and when it is executed.
