### ISSUE TITLE
Code style issue: circular dependencies

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#413]
**Google styleguide**

> Circular dependencies that are caused by typing are code smells. Such code is a good candidate for refactoring.
https://google.github.io/styleguide/pyguide.html#31914-circular-dependencies

**Example**

https://github.com/spcl/dace/blob/79fb9bd8e149172ef2ef213e77801e177478d47a/dace/sdfg/sdfg.py#L1124

**Possible solution**

If circular dependency between classes A and B is really required, then they can’t exist without each other and it makes sense to merge them (for example, into one file).

**Comment by tbennun** [comment]
Well, an `SDFG` contains a list of `SDFGState`s as nodes, each of which can contain a `NestedSDFG` node, which contains an `SDFG` object. Not much more to discuss.

Are there any actually fixable loops in the code?

As for your possible solution, we had this before: sdfg.py used to be over 5000 lines of Python, which in an of itself is a gross violation of some standard... It was hard to find relevant code when it was all hidden in one big file.

**Comment by definelicht** [comment]
I don't see a viable alternative. If there is one, propose it here.

**Comment by alexnick83** [comment]
I also don't see a better solution here. This is a Python issue.

**Comment by acalotoiu** [comment]
I prefer circular dependencies to unreadable files.

**Comment by tbennun** [comment]
Could we close this issue?
