### ISSUE TITLE
Code style issue: function solves more than a single task

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#414]
**Google style guide**

> Prefer small and **focused** functions.
https://google.github.io/styleguide/pyguide.html#318-function-length

**Examples**

- Tasks are parametrized by argument value (node_to_children=True/False).
https://github.com/spcl/dace/blob/a3a1fb9b60d2414bb90a5837f83d30e4a0182b43/dace/sdfg/state.py#L282
- Tasks are parametrized by argument type. Parameters can accept different types, some types trigger additional logic that is checked with if/else.
https://github.com/spcl/dace/blob/2e12becf188ab413f2244a990b9b9d912a892518/dace/transformation/transformation.py#L447
https://github.com/spcl/dace/blob/2e12becf188ab413f2244a990b9b9d912a892518/dace/sdfg/sdfg.py#L1690

**Cons**

* The more variation of parameters function support, the harder it gets to find the right one. It requires reading the code and picking "the most default case".

**Possible solution**

Decompose functions into simpler ones. Use basic functions that accept a single type/value and do the work only for this case. 
On top of it, design proxy functions that convert specific types to base types (do if/else logic) and call base functions.

**Comment by tbennun** [comment]
Disagree with the Transformation interface, but fully agree on `scope_dict`.

**Comment by definelicht** [comment]
I dislike the `node_to_children=True`, I'm in favor of splitting it into two (they can always share a helper function).

**Comment by alexnick83** [comment]
`Transformation::apply_to` is a common interface for all transformations. It does some preprocessing on the method arguments and then simply calls `apply`. The use-case here is that you have a single `apply_to`. You don't want to have `apply_dataflowtrans_to`, `apply_interstatetrans_to`, etc.

However, I agree with everyone that `scope_dict` could really be `scope_dict` and `parent_to_childern` or something like that.

**Comment by tbennun** [comment]
Stay tuned for a fix of `scope_dict` in #417
