### ISSUE TITLE
Code style issue: lack of clean API for the common use cases

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#415]
**Examples**

Why not to provide `nodes.Tasklet()` or classmethod `Tasklet.new_instance()`?
https://github.com/spcl/dace/blob/79fb9bd8e149172ef2ef213e77801e177478d47a/dace/transformation/dataflow/stream_transient.py#L60
https://github.com/spcl/dace/blob/79fb9bd8e149172ef2ef213e77801e177478d47a/dace/transformation/dataflow/stream_transient.py#L61
https://github.com/spcl/dace/blob/79fb9bd8e149172ef2ef213e77801e177478d47a/dace/transformation/interstate/sdfg_nesting.py#L41

**Comment by tbennun** [comment]
What you see here is not the common case. We don't want to construct "empty" nodes in any case. Unfortunately this is an artifact of a bad initial design, see proposal in #412 and consider closing as duplicate.

**Comment by alexnick83** [comment]
To combine with the proposal in #412, it could be `Node::pattern_node`, so you would just call `Tasklet.pattern_node()`.

**Comment by tbennun** [comment]
But then it's a static function XD

**Comment by tbennun** [comment]
A fix will be provided in #417
