### ISSUE TITLE
Code style issue: string based API

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#416]
Never use string-based API

**Examples**

- Accepts string which is parsed to object. Why not accept objects in the first place?
https://github.com/spcl/dace/blob/79fb9bd8e149172ef2ef213e77801e177478d47a/dace/memlet.py#L60
- Connection between Array names, AccessNodes, connectors, symbols is implemented with a string-based interface.
- Entities require names/labels. While it is good for understanding what is going on, clashes in names should not impact anything. Program behavior shouldn't rely on the way how variables (arrays, accessnodes) are named.

**Cons**

- slow 
- requires converting objects to strings and back from the user
- creates hard to track links between entities

**Pros**

- allows linking objects without creating circular dependencies.

**Possible solution**

Consider other designs to eliminate circular dependencies. 
* Use integer IDs of objects to define links between them.
* Store links in containers (SDFGState) of entities (Array, AccessNode) that could have circular dependencies otherwise.

**Exception**

API that parses user input

**Comment by tbennun** [comment]
The Memlet API, in addition to accepting strings for backwards compatibility and ease-of-use, also accepts the objects themselves. 
* `Subset`s can be used as subsets
* Symbolic expressions are used as volume and others

The strings are not used to avoid circular dependencies.

As for arrays, we used to keep them as their data descriptor objects, but this caused many issues in the past with duplicate objects with different properties etc., so we moved to a centralized data descriptor storage on the SDFG itself (`sdfg.arrays`), which uses strings as names.

Feel free to suggest a new interface.

**Comment by tbennun** [comment]
Now, I would appreciate other string-based APIs as examples, which were actually issues:
https://github.com/spcl/dace/blob/master/dace/sdfg/state.py#L1091

We tried to fix most of them, but I'm sure there are still a few around.

**Comment by alexnick83** [comment]
As far as I remember, the string-based API in the memlets is there to allow people to create memlets without having to create the subsets themselves. It is kinda weak I guess since if someone is comfortable enough to create memlets, they should be able to create ranges as well. However, it would be interesting to hear people's opinions on this.

**Comment by tim0s** [comment]
I think it is much better to have objects here (in the example given) instead of strings.

**Comment by tbennun** [comment]
> As far as I remember, the string-based API in the memlets is there to allow people to create memlets without having to create the subsets themselves. It is kinda weak I guess since if someone is comfortable enough to create memlets, they should be able to create ranges as well. However, it would be interesting to hear people's opinions on this.

Compare the following two examples:
```python
memlet = dace.Memlet(data='A', src_subset=dace.subsets.Range([(i, i, 1)], volume=1)
```
(assuming that `i` is already defined as a symbol outside)

with:
```python
memlet = dace.Memlet('A[i]')
```

Both are valid syntax in the current API (and would result in the same memlet), but one requires in-depth knowledge about how subsets and memlets work in dace, and the other can just be added easily. It's the standard clash of ease-of-use and user-friendliness vs. clear objects.

Look, before the refactor, there was `dace.Memlet(objects...)` and `dace.Memlet.simple(string)`. Guess what everybody used most of the time? (and by most I mean ~800 uses vs. ~20)

**Comment by acalotoiu** [comment]
I would be fine with having the only the first option, if I would have access to a helper function to translate a string to the set of objects, that can also fail gracefully if I feed it a string it cannot parse.
