### ISSUE TITLE
Erroneous data-to-data copy with other_subset

### ISSUE THREAD

**Issue by alexnick83** [spcl/dace#438]
The bug can be reproduced by running `test_out_success` in `tests/transformations/redundant_copy_test.py`.
The test produces an SDFG with an edge from access node A to access node C. The edge has source subset `0, 0:3, 4` and destination subset `1, 2, 0:3, 4`.
However, if you uncomment the assertion on line 91, it will fail.
The compiled program appears to copy the correct subset of A, but on `C[0:3, 2, 0, 4]` instead of `C[1, 2, 0:3, 4]`.

**Comment by alexnick83** [comment]
Linked to the wrong PR

**Comment by tbennun** [comment]
Seems like it was erroneously reopened.
