### ISSUE TITLE
Scalar type promotion issue

### ISSUE THREAD

**Issue by orausch** [spcl/dace#454]
Currently, the following fails compilation:
```python
import dace
import numpy as np

@dace
def add_one(A: dace.int32[10, 10], B: dace.int32[10, 10]):
    B[:] = A + 1

A = np.zeros((10, 10)).astype(np.int32)
B = np.zeros((10, 10)).astype(np.int32)
add_one.to_sdfg(strict=false)(A=A, B=B)
print(B)
```
In numpy this works:
```python
>>> a = np.zeros((2,2)).astype(np.int32)
>>> a + 1
array([[1, 1],
       [1, 1]], dtype=int32)
```

This is caused by the fact that the dtype of `A + 1` is inferred to be `int64`. In numpy it would be `int32` due to their scalar-array type promotion rules (which are quite ugly: https://github.com/numpy/numpy/issues/13591).

To sidestep this I think it would be best to implement the type constructors in the python frontend (i.e. `dace.int32`).

**Comment by alexnick83** [comment]
The latest master should solve a lot of these issues. Now `A + 1` should have the type of A. There are also type constructors available.
