### ISSUE TITLE
Dimensionality mismatch between src/dst subsets

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#51]
```python
import numpy as np
import dace

@dace.program
def foo123(a : dace.float32[2,3], b : dace.float32[2,3]):
    b[0,:] = a[0,:]
    
A = np.full((2,3), 3, dtype=np.float32)
B = np.full((2,3), 4, dtype=np.float32)

foo123(A, B)

print(A)
print(B)
```

**Error:**

InvalidSDFGEdgeError: Dimensionality mismatch between src/dst subsets (at state assign_6_4, edge b[0, 0:3] -> [0:2] (__tmp0:None -> b:None))

**Expected output:**

If you replace `b[0,:] = a[0,:]` by `b[0] = a[0]` everything works as expected.

**Comment by tbennun** [comment]
Fixed in #88 .
