### ISSUE TITLE
Upgrade Xilinx backend to support Vitis

### ISSUE THREAD

**Issue by definelicht** [spcl/dace#52]
We need to upgrade the Xilinx compilation flow to target Vitis, which is the rebranded/repackaged version of SDx/SDAccel. This requires:
- [x] Updating hlslib to the newest version, which supports Vitis
- [x] Update CMake variable names to reflect changes in the Find-script
- [x] Possibly change some compiler flags to reflect the change from `xocc` to `v++`

**Comment by tbennun** [comment]
@definelicht is this essentially done?

**Comment by definelicht** [comment]
Yes, this is done when intel_fpga is merged
