### ISSUE TITLE
Codegen: Generates self-assignments in/around parallel maps

### ISSUE THREAD

**Issue by phschaad** [spcl/dace#555]
**Description**
Generated code contains self-assignments of variables (e.g. `unsigned int fsz0 = fsz0;`) in and around parallel maps.

**Steps to reproduce:**
1. Run the BFS sample (`python samples/graph/bfs_bsp.py`)
2. Computes the wrong output -> high error/diff in most cases
3. Generated code in `.daceche/bfs_bsp/src/cpu/bfs_bsp.cpp` contains self assignments.

**Expected behavior:**
Sample runs with an error/diff of `0.0`.

**Screenshots of self assignments in generated code:**
![Screenshot 2021-01-21 145517](https://user-images.githubusercontent.com/9193712/105360268-b1ec4300-5bf8-11eb-99b4-da9a17f00b3a.png)

**Environment:**
 - OS: Windows 10 with WSL2 (Ubuntu20.04)

**Comment by tbennun** [comment]
@phschaad was that fixed since?

**Comment by phschaad** [comment]
Looks like it has, yes.
