### ISSUE TITLE
Pipeline scope generates wrong code if ceiling is used in one of the pipeline range

### ISSUE THREAD

**Issue by TizianoDeMatteis** [spcl/dace#572]
**Describe the bug**
If ceiling is used in one of the pipeline ranges, then the FPGA backend will generate code without replacing `ceiling` with `int_ceil`. This will let compilation fail.

The same occurs with `floor`, but, this is a valid (OpenCL) function

**Expected behavior**
Generate code with `int_ceil` instead of `ceiling`

**Comment by tbennun** [comment]
Is this fixed now?

**Comment by TizianoDeMatteis** [comment]
Yep. Closing.
