### ISSUE TITLE
Change how FPGA compiler is specified in the DaCe config

### ISSUE THREAD

**Issue by definelicht** [spcl/dace#59]
Right now, we are specifying the compiler with an executable name (e.g., "xocc"). Instead, we should pass the root folder of the installation (e.g., `/opt/Xilinx/Vitis/2019.2`). Furthermore, we should default to not setting this in the config, and instead letting the CMake script find the local installation.

**Comment by definelicht** [comment]
@tbennun You want to update CUDA also?

**Comment by tbennun** [comment]
Yes, it makes more sense this way, MPI too.

**Comment by tbennun** [comment]
Fixed
