### ISSUE TITLE
Renderer improvements break some visualizations

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#60]
Try to run "tutorials/sdfg_api.ipynb" in jupyter:

**Before renderer improvements https://github.com/spcl/dace/pull/58 (f2c358f)**
![image](https://user-images.githubusercontent.com/9387186/70517083-549e4b00-1b38-11ea-951e-a3170f38e2fd.png)

**After renderer improvements https://github.com/spcl/dace/pull/58 (5bdc38e)**
![image](https://user-images.githubusercontent.com/9387186/70517480-f160e880-1b38-11ea-8391-c41d12e6375a.png)

**Comment by tbennun** [comment]
Yes, this is the intent, it's not broken. Zooming in will show the nodes (they're not readable at this scale anyway).

**Comment by am-ivanov** [comment]
You should see it in action:
![111](https://user-images.githubusercontent.com/9387186/70546447-97c7e080-1b6f-11ea-815d-8afae3a7bfea.gif)

**Comment by tbennun** [comment]
Apologies, the fix was in my branch but was not pushed to master. Now it is fixed.
