### ISSUE TITLE
Jacobi simple sample for FPGA

### ISSUE THREAD

**Issue by TizianoDeMatteis** [spcl/dace#618]
**Describe the bug**
The Jacobi simple sample fails to produce  correct FPGA code (both Xilinx, Intel).
This is due to some missing kernel parameter in the generated code, that are originated by SDFG symbols

**To Reproduce**
Execute `samples/simple/jacobi.py`, transform it for FPGAs.

**Comment by tbennun** [comment]
Superseded by https://github.com/spcl/dace/blob/main/tests/npbench/polybench/jacobi_1d_test.py#L90
But it should be in the samples @TizianoDeMatteis
