### ISSUE TITLE
Array operation between reshaped arrays produces erroneous result

### ISSUE THREAD

**Issue by alexnick83** [spcl/dace#631]
The following is taken from the NPBench benchmark `resnet` and involves the `conv2d` layer. Originally, DaCe did not support `np.newaxis` and the compatibility code used was:
```python
    for i in range(S1-S4+1):
        for j in range(S2-S4+1):
            output[:, i, j, :] = np.sum(
                np.reshape(input[:, i:i+S4, j:j+S4, :], (S0, S4, S4, S3, 1)) *
                np.reshape(weights, (1, S4, S4, S3, S5)),
                axis=(1, 2, 3),
            )
```

Since `np.newaxis` was added, we were able to switch to the more-close-to-numpy version:
```python
    for i in range(S1-S4+1):
        for j in range(S2-S4+1):
            output[:, i, j, :] = np.sum(
                input[:, i:i + S4, j:j + S4, :, np.newaxis] *
                weights[np.newaxis, :, :, :],
                axis=(1, 2, 3),
            )
```

The new version works fine, but the old version doesn't validate any longer. The issue probably exists somewhere between changes to how views work and improvements to the RedundantCopy transformations. The issue may arise also in `stockham_fft`, particularly in the following line:
```python
tmp_twid = np.reshape(tmp_perm, (N, )) * np.reshape(D, (N, ))
```

**Comment by tbennun** [comment]
@alexnick83 should be fixed now with views?

**Comment by tbennun** [comment]
@alexnick83 I think this works now, please reopen if it's still an issue.
