### ISSUE TITLE
Allow transforming @dace.program

### ISSUE THREAD

**Issue by definelicht** [spcl/dace#691]
Currently, in order to apply transformations to a `@dace.program`, you have to first convert it to an SDFG.

This is sometimes suboptimal because it changes the arguments required to call the program. For example:

```python
matmul(A, B, C)
sdfg = matmul.to_sdfg()
sdfg(A=A, B=B, C=C, N=N, K=K, M=M)
```

It would be convenient to not have to change the program arguments like this when converting to an SDFG, perhaps by allowing transformations to be applied to the underlying SDFG of a `@dace.program` while maintaining the program interface/API.

**Comment by definelicht** [comment]
@tbennun Since you're tinking with `@dace.program`, is this an easy feature to add?

**Comment by tbennun** [comment]
I added this too, see 64b87ce1

**Comment by tbennun** [comment]
However, I don't think it has a proper transformation interface.

**Comment by definelicht** [comment]
If I understand correctly, you allow calling a compiled version of a program to be called with the original calling style, but there's still no full SDFG/transformation interface, right? So this feature request is still relevant

**Comment by tbennun** [comment]
Now done in 69c45a376808369e4dd5f4d5a227d2ca51106350

**Comment by definelicht** [comment]
> 
> 
> Now done in 69c45a376808369e4dd5f4d5a227d2ca51106350

Can't clicky clicky, can't see the commit in the PR either 🤔

**Comment by tbennun** [comment]
69c45a376808369e4dd5f4d5a227d2ca51106350

**Comment by tbennun** [comment]
@definelicht Strange :/
