### ISSUE TITLE
WCR appear on CPU instead of GPU after GPUTransformSDFG 

### ISSUE THREAD

**Issue by am-ivanov** [spcl/dace#73]
**Describe the bug**
Segfault during illegal memory access from CPU to cudaMalloc allocated memory. Codegen creates code for WCR on CPU instead of GPU.

**To Reproduce**
1. Create SDFG with WCR
2. Apply GPUTransformSDFG
3. Execute SDFG

**Comment by tbennun** [comment]
Any sdfg for example?
