### ISSUE TITLE
When using the python frontend, assigning slices to names does not create a view. 

### ISSUE THREAD

**Issue by gronerl** [spcl/dace#774]
In the following example, the behavior is different from typical NumPy behavior (i.e. when the `@dace.program` decorator is commented out.

The behavior is equivalent to `B = A[1:-1]` causing a copy instead of a view in pure numpy. (A temporary is created in the SDFG when it should just be a subset of the original array.) Namely, the changes to the view are not propagated back to A. 

```
import numpy as np
import dace


@dace.program
def call_me(A: dace.float64[10]):
    B = A[1:-1]
    B[...] = 2.0
    B += 1.0

A = np.ones((10,), dtype=np.float64)

call_me(A)

assert np.all(A[1:-1]==3.0)
assert A[0] == 1.0
assert A[-1] == 1.0
```

**Comment by alexnick83** [comment]
https://github.com/spcl/dace/blob/71761364e009e560b1dd5c29ac90177d2f8d5038/tests/numpy/copies_and_views_test.py#L64-L79
