### ISSUE TITLE
Slices as arguments to functions in `@dace.program`s  not cause copies. 

### ISSUE THREAD

**Issue by gronerl** [spcl/dace#775]
As can be reproduced with the following example, slices that are passed from one `@dace.program` to another cause the changes to the array not appear in the original array. This behavior is different from pure python+numpy. It seems that this is only the case if an array is both input and output to a function.

```
import numpy as np
import dace

@dace.program
def inner(A: dace.float64[8]):
    tmp = 2 * A[1:]
    A[:-1] = tmp

@dace.program
def call_me(A: dace.float64[10]):
    inner(A[1:-1])

A = np.ones((10,), dtype=np.float64)

call_me(A)

assert np.all(A[1:-2] == 2.0)
assert A[0] == 1.0
assert np.all(A[-2:] == 1.0)
```

**Comment by tbennun** [comment]
Thanks! I think this is related to #774, but handled somewhere else in the python frontend code, so we can keep the two issues separate.

**Comment by alexnick83** [comment]
https://github.com/spcl/dace/blob/71761364e009e560b1dd5c29ac90177d2f8d5038/tests/numpy/copies_and_views_test.py#L81-L100
