### ISSUE TITLE
ExtendedMemoryPointer does not name a type

### ISSUE THREAD

**Issue by bartokon** [spcl/dace#905]
**Describe the bug**
OpenCL library error.

**To Reproduce**
1. Source Vitis 2021.1 settings.sh
2. Try to run any fpga example
3. See error

**Expected behavior**
There should be no error!

**Screenshots**
![image](https://user-images.githubusercontent.com/47795888/146690373-aab3c950-0e74-4c33-be57-0728c4984d35.png)
**Desktop (please complete the following information):**
 - OS: Ubuntu LTS 20.04

**Comment by tbennun** [comment]
@definelicht

**Comment by definelicht** [comment]
Hi @bartokon. Could you try without sourcing `settings.sh`? This can cause various problems with include paths. Just make sure that `v++` is on your `PATH` (or set the compiler -> xilinx -> path variable in your `~/.dace.conf`).

**Comment by bartokon** [comment]
Hi, I've got it.
![image](https://user-images.githubusercontent.com/47795888/146947515-44d98e3f-b73a-4634-87f0-5902ed7b696f.png)
Is there some kind of set-up tutorial for Dace?
Thanks for help!

**Comment by definelicht** [comment]
In principle DaCe shouldn't require any other setup that running the installer :-) But of course than can be various environment-related issues, like the one you experienced. You can check the tutorials subdirectory for general tutorials on DaCe.
