### ISSUE TITLE
Issues related with numpy reduction operation

### ISSUE THREAD

**Issue by huanglangwen** [spcl/dace#940]
# Invalid SDFG
**Describe the bug**
When using `arr.max()` inside a dace program, an invalid SDFG is generated and cannot be loaded by the SDFG viewer. The viewer complains that a non-digit "-Infinity" is detected as a value of the "Identity". Manually correcting "-Infinity" to minimum representable floating point number solves the problem. Yet it is unclear how does "-Infinity" get serialized into the SDFG json. Note that using `np.max(arr)` lead to such problem. 

**To Reproduce**
```python
@dace.program
def foo(a: dace.float[3]):
  return a.max() 

foo(np.array([1.,2.,3.])) # cannot be loaded by SDFG viewer

@dace.program
def bar(a: dace.float[3]):
  return np.max(a) 

bar(np.array([1.,2.,3.])) # works fine
```

# Code generation issue
**Describe the bug**
When applying a reduction operation on a temporary array in a dace program, it fails to compile with the CPU backend. The generated cpp file looks like following:
```cpp
inline void reduce_0_0_2(foo_t *__state, double _in, double* _out) {
    //ignore some code here...
    for (auto _i0 = 0; _i0 < 3; _i0 += 1) {
            double inp = _in[_i0]; // <----- a double cannot be accessed as an array!
            double out;
            out = inp;
            dace::wcr_fixed<dace::ReductionType::Max, double>::reduce_atomic(_out, out);
    }
}
```
**To Reproduce**
```python
@dace.program
def foo():
    a = np.array([1.,2.,3.])
    b = np.max(a)
```

# Inconsistent result
**Describe the bug**
A dace program containing reduction on its input may produce inconsistent result compared with doing reduction manually, while the latter one is consistent with the python version.

**To Reproduce**
```python
gamma = 1.4

@dace.program
def eigenvalues(u: dace.float64[3]):
    rho = u[0]
    rhov = u[1]
    E = u[2]
    v = rhov / rho
    p = (E - 0.5*rhov*v)*(gamma - 1)
    c = np.sqrt(gamma*p / rho)
    ret = np.empty_like(u)
    ret[0] = v - c
    ret[1] = v
    ret[2] = v + c
    return ret

@dace.program
def flux_min1(ul: dace.float64[3], ur: dace.float64[3]):
    fl = np.array([0.0442802,  0.13597403, 0.12488015])
    fr = np.array([0., 0.1, 0.])
    eigvalsl = eigenvalues(ul)
    eigvalsr = eigenvalues(ur)
    sl = np.min(eigvalsl)
    sr = np.max(eigvalsr)
    if sl >= 0:
        return fl
    elif sr <= 0:
        return fr
    else:
        return (sl*sr*(ur - ul) + fl*sr - fr*sl)/(sr-sl)

@dace.program
def flux_min2(ul: dace.float64[3], ur: dace.float64[3]):
    fl = np.array([0.0442802,  0.13597403, 0.12488015])
    fr = np.array([0., 0.1, 0.])
    eigvalsl = eigenvalues(ul)
    eigvalsr = eigenvalues(ur)
    sl = min(eigvalsl[0], eigvalsl[1], eigvalsl[2])
    sr = max(eigvalsr[0], eigvalsr[1], eigvalsr[2])
    if sl >= 0:
        return fl
    elif sr <= 0:
        return fr
    else:
        return (sl*sr*(ur - ul) + fl*sr - fr*sl)/(sr-sl)

ul = np.array([0.15532005, 0.0442802,  0.31468739])
ur = np.array([0.125, 0.,    0.25 ])
flux_min1(ul, ur) - flux_min2(ul, ur) # Should be [0., 0., 0.]  !!!
```

**Comment by tbennun** [comment]
Thanks for reporting!

For the first issue: 

As sympy is used to store to json, it seems that the "identity" property of reduce nodes is not given a type: https://github.com/spcl/dace/blob/master/dace/libraries/standard/nodes/reduce.py#L1061

Maybe we should consider using `SymbolicProperty` as it can be stored/loaded properly, and the identity value is a symbolic expression anyway.
