### ISSUE TITLE
StateAssignElimination doesn't consider symbols used on subarray restrictions

### ISSUE THREAD

**Issue by leporia** [spcl/dace#995]
**Describe the bug**
When `StateAssignElimination` is applied (from the `simplify()` call) it will remove symbols that are used in memlets in the subset restriction.

**To Reproduce**
[sdfgs.zip](https://github.com/spcl/dace/files/8715149/sdfgs.zip)
Apply the transformation on `untransformed.sdfg` to obtain `transformed.sdfg`
For example by running this code:
```
from dace.sdfg import *
from dace.transformation.interstate import StateAssignElimination

sdfg = SDFG("main").from_file("untransformed.sdfg")
sdfg.apply_transformations_repeated(StateAssignElimination,
                                    validate=True,
                                    permissive=False,
                                    validate_all=False)
sdfg.save("transformed_gen.sdfg")
```

Note that the transformation is also run by running `.simplify()` on the SDFG.

**Expected behavior**
The interstate edge between `state` and `_state_6_7` should keep the assignment `dace_arr_0_start = dace_arr_0_start + 1`.
Same thing for the edge between `GuardState6` and `_state18_19`. This because the memlet from `dace_arr_1` and `dace_arr_0` is using the value.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 35 (Workstation Edition)
 - DaCe version 0.13.1

**Comment by alexnick83** [comment]
I think that real issue here is that `dace_arr_0` is used in the nested SDFG as both `dace_arr_0` and `dace_arr_1`. The transformations do not take into account aliasing. Can you write how did you generate the `untransformed.sdfg`?

**Comment by leporia** [comment]
But the edges on the top sdfg that read and write to `dace_arr_0` use `dace_arr_0_start` anyway. In the nested sdfg only `dace_arr_1` is present that doesn't actually use `dace_arr_0_start`.
Maybe I'm not understanding how symbols mapping work. Does it work in both (read and write) ways? Like if I modify a symbol in a nested sdfg is the write also propagated in the next states in the top sdfg?

`untransformed.sdfg` was generated by a C to DaCe compiler that I'm working on from the following C code
```
int main(int argc, char** argv) {

	double size = 3;
	double* arr = malloc(size * sizeof(double));

	for (int i = 0; i < size; i++) {
		arr[0] = i*3.0;
		arr++;
	}

	arr = arr - 3;

	return arr[0] + arr[2];
}
```

**Comment by alexnick83** [comment]
Oh, I see. I misread `dace_arr_0_start` as `dace_arr_0` in the interstate edge. I will get back to you.

**Comment by alexnick83** [comment]
@leporia The issue is with (as you probably suspected) the way symbol mapping works. According to SDFG semantics, any changes made to symbols in a nested SDFG should not be visible to the parent SDFG. This constraint is important, otherwise many optimization opportunities would be lost. Therefore, the actual bug is in code generation, which results in your original untransformed SDFG validating against your C program.

A proper solution to the problem is to move `dace_arr_0_start`'s increment to the parent SDFG (see attached picture). My understanding is that you work with @acalotoiu but feel free to also contact me if you need assistance on how to achieve this at the frontend level.

**Comment by leporia** [comment]
I see, thanks for the support. Yes I'm working with @acalotoiu and I think we already found a solution to the problem on our side.
